// Restaurant data — single source of truth
// Edit restaurants HERE, cards and map markers are generated automatically

var restaurants = [
  {
    id: "川宗",
    category: "chinese",
    name: "川宗",
    nameEn: "Red Pepper",
    lat: 47.662684, 
    lng: -122.313295,
    address: "4545 University Way NE",
    tags: ["川菜"],
    price: "$$ · $15-30",
    visited: true,
    badges: ["🔥 Ave OG 老牌"],
    dishes: [
      { name: "$9.9 穷鬼套餐", note: "ZZ 亲自品尝" },
      { name: "番茄肥牛", note: "ZZ 推荐" },
      { name: "藤椒肥牛（宽粉吸满汤汁）", note: "必点" },
      { name: "新疆炒米粉 / 水煮牛肉 / 辣子鸡" },
    ],
    notes: [
      { type: "info", text: "💡 最好和朋友一起去！ZZ 亲自品尝过番茄肥牛；华大学生食堂级别" },
    ],
  },
  {
    id: "西安味道",
    category: "chinese",
    name: "西安味道",
    nameEn: "Taste of Xi'an",
    lat: 47.662091,
    lng: -122.313330,
    address: "4523 University Way NE",
    tags: ["西北菜"],
    price: "$$ · ~$20",
    visited: true,
    badges: ["🔥 面食顶流"],
    dishes: [
      { name: "手工扯面 / 油泼辣子面", note: "必点" },
      { name: "肉夹馍" },
      { name: "大盘鸡（分量巨大）" },
      { name: "三秦套餐：凉皮+肉夹馍+豆浆" },
    ],
    notes: [
      { type: "info", text: "💡 面条筋道、分量足，西北面食在 Ave 上最佳选择" },
    ],
  },
  {
    id: "川渝食府",
    category: "chinese",
    name: "川渝食府",
    nameEn: "Chuan House",
    lat: 47.661732,
    lng: -122.313331,
    address: "4509 University Way NE",
    tags: ["川菜"],
    price: "$$ · $20-35",
    visited: true,
    dishes: [
      { name: "干锅花菜", note: "朋友推荐" },
      { name: "水煮牛羊", note: "朋友推荐" },
      { name: "干锅肥肠", note: "朋友推荐" },
      { name: "西红柿炒鸡蛋", note: "朋友推荐" },
      { name: "辣子鸡" },
      { name: "活鱼版烤鱼", note: "推荐" },
      { name: "夫妻肺片" },
    ],
    notes: [
      { type: "info", text: "💡 川菜地道，烤鱼是活鱼的更鲜（虽然贵一些）；朋友经常吃，推荐干锅花菜、水煮牛羊、干锅肥肠、西红柿炒鸡蛋" },
    ],
  },
  {
    id: "杨国福麻辣烫",
    category: "chinese",
    name: "杨国福麻辣烫",
    nameEn: "YGF MalaTang",
    lat: 47.663821,
    lng: -122.312926,
    address: "4730 University Way NE #103",
    tags: ["麻辣烫"],
    price: "$$ · $15-25",
    visited: true,
    dishes: [
      { name: "牛骨汤底麻辣烫", note: "必点" },
      { name: "自选菜品 + 多种汤底" },
    ],
    notes: [
      { type: "info", text: "💡 牛骨汤很香，\"一秒回国\"的感觉；价格偏贵但品质稳定" },
      { type: "info", text: "🍦 可兑换冰淇淋" },
    ],
  },
  {
    id: "福原麻辣烫",
    category: "chinese",
    name: "福原麻辣烫",
    nameEn: "Fuyuan MalaTang",
    lat: 47.66549,
    lng: -122.31274,
    address: "5000 University Way NE, Ste A",
    dataAddr: "FY Malatang, 5000 University Way NE, Ste A, Seattle, WA 98105",
    tags: ["麻辣烫"],
    price: "$ · $12-20",
    visited: true,
    dishes: [
      { name: "中辣牛骨汤 / 麻酱干拌", note: "推荐" },
      { name: "性价比高" },
    ],
    notes: [
      { type: "info", text: "💡 比杨国福便宜，Miso 汤底是隐藏好选择" },
      { type: "info", text: "🍦 可兑换冰淇淋" },
    ],
  },
  {
    id: "美心饼家",
    category: "chinese",
    name: "美心饼家",
    nameEn: "Mee Sum Pastry",
    lat: 47.66106,
    lng: -122.31332,
    address: "4343 University Way NE",
    tags: ["台湾菜 / 烘焙"],
    price: "$ · $10-18",
    visited: true,
    badges: ["🍬 甜口友好"],
    dishes: [
      { name: "左宗棠鸡", note: "ZZ 亲自品尝" },
      { name: "卤肉饭 / 萝卜牛腩" },
      { name: "菠萝包 / 咖喱牛肉包", note: "推荐" },
    ],
    notes: [
      { type: "info", text: "💡 百年历史老店，台湾菜+烘焙结合；ZZ 亲自品尝过左宗棠鸡" },
    ],
  },
  {
    id: "牛一嘴",
    category: "chinese",
    name: "牛一嘴",
    nameEn: "Nuodle Express",
    lat: 47.65961,
    lng: -122.31333,
    address: "4245 University Way NE",
    tags: ["西北面食"],
    price: "$$ · $15-22",
    visited: true,
    badges: ["🔥 连锁兰州拉面"],
    dishes: [
      { name: "香辣牛大骨面", note: "ZZ 亲自品尝" },
      { name: "手工拉面" },
    ],
    notes: [
      { type: "info", text: "💡 连锁店，面条劲道、西北风味正宗；ZZ 亲自品尝过香辣牛大骨面" },
    ],
  },
  {
    id: "煎饼师傅",
    category: "chinese",
    name: "煎饼师傅",
    nameEn: "Master Bing",
    lat: 47.66232,
    lng: -122.31329,
    address: "4537A University Way NE",
    tags: ["小吃 / 北方"],
    price: "$ · $15-20",
    visited: false,
    badges: ["🔥 煎饼果子"],
    dishes: [
      { name: "煎饼果子（孜然羊肉 / 培根肉松）", note: "必点" },
      { name: "烤鸭卷饼" },
      { name: "鸭血粉丝汤" },
      { name: "脆皮小包子" },
    ],
    notes: [
      { type: "caution", text: "⚠️ 推荐去 Bellevue Square 那一家，Ave 上的这家品质差远了" },
      { type: "info", text: "💡 三家分店（Bellevue/Portland），正宗天津煎饼果子+南京鸭血粉丝" },
    ],
  },
  {
    id: "小达客",
    category: "chinese",
    name: "小达客",
    nameEn: "Little Duck",
    lat: 47.65711,
    lng: -122.31755,
    address: "4100 Roosevelt Way NE, Unit B",
    dataAddr: "Little Duck, 4100 Roosevelt Way NE, Unit B, Seattle, WA 98105",
    tags: ["东北菜"],
    price: "$$ · $20-35",
    visited: false,
    badges: ["🍬 甜口锅包肉"],
    dishes: [
      { name: "锅包肉（酸甜口）", note: "🍬 必点" },
      { name: "熘肉段" },
      { name: "东北大拉皮" },
    ],
    notes: [
      { type: "info", text: "🍬 锅包肉酸甜口，甜口偏好者会喜欢！酥脆下饭，聚餐好选择" },
    ],
  },
  {
    id: "一二三·自选快餐",
    category: "chinese",
    name: "一二三·自选快餐",
    nameEn: "Bite and Bento",
    lat: 47.65954,
    lng: -122.31333,
    address: "4241 University Way NE",
    dataAddr: "Bite and Bento, 4241 University Way NE, Seattle, WA 98105",
    tags: ["中式快餐"],
    price: "$ · $14.99",
    visited: true,
    badges: ["🍬 糖醋排骨"],
    dishes: [
      { name: "红烧排骨 / 糖醋排骨", note: "🍬 推荐" },
      { name: "4 菜任选 $14.99" },
    ],
    notes: [
      { type: "info", text: "💡 干净家常、自选便当，方便快捷；糖醋排骨适合甜口" },
    ],
  },
  {
    id: "Win Feng Noodles",
    category: "chinese",
    name: "冯瀛桂林米粉",
    nameEn: "Win Feng Noodles",
    lat: 47.6655,
    lng: -122.3155,
    address: "4757 12th Ave NE（Ave 旁边）",
    dataAddr: "Win Feng Noodles, 4757 12th Ave NE, Seattle, WA 98105",
    tags: ["桂林米粉"],
    price: "$$ · ~$16",
    visited: true,
    badges: ["⚠️ 即将关门"],
    dishes: [
      { name: "双拼米粉（牛肚+猪舌）", note: "$15.99" },
      { name: "现做米粉 + 自助小料台" },
    ],
    notes: [
      { type: "caution", text: "⚠️ 听说快要关门了，想吃的抓紧去！" },
      { type: "info", text: "💡 附近最好吃的米粉，粉是现做的。小料台自己加汤、醋、卤子、辣酱，还有免费柠檬水" },
    ],
  },
  {
    id: "鼎泰丰",
    category: "chinese",
    name: "鼎泰丰",
    nameEn: "Din Tai Fung",
    lat: 47.66159,
    lng: -122.29955,
    address: "U Village, 2621 NE 46th St",
    tags: ["台湾 / 小笼包"],
    price: "$$$ · $25-45",
    visited: true,
    badges: ["🔥 朋友聚餐首选"],
    dishes: [
      { name: "小笼包", note: "必点" },
      { name: "红油抄手" },
      { name: "巧克力小笼包", note: "🍬 甜口必试" },
    ],
    notes: [
      { type: "info", text: "💡 不在 Ave 上但在旁边 U Village，步行可达。可以和朋友一起去。巧克力小笼包是甜口惊喜！品质稳定但确实有点贵" },
    ],
  },
  {
    id: "李记",
    category: "chinese",
    name: "李记",
    nameEn: "Lee's Kitchen",
    lat: 47.659296, 
    lng: -122.314523,
    address: "4106 Brooklyn Ave NE #102B（Ave 旁边，离 Ode 很近）",
    dataAddr: "Lee's Kitchen, 4106 Brooklyn Ave NE #102B, Seattle, WA 98105",
    tags: ["中餐 / 简餐"],
    price: "$ · $12-20",
    visited: true,
    dishes: [
      { name: "猪杂面", note: "推荐" },
      { name: "煲仔饭", note: "必点" },
      { name: "盐酥鸡便当" },
      { name: "猪脚饭", note: "推荐" },
    ],
    notes: [
      { type: "info", text: "💡 ZZ 经常去吃！猪杂面、煲仔饭、盐酥鸡便当、猪脚饭都很不错。就在茶宴旁边，离 Ode 很近，下课顺路买很方便" },
      { type: "info", text: "卫生做得不是很好，注意一下就好" },
    ],
  },
  {
    id: "侨林火锅",
    category: "chinese",
    name: "侨林火锅",
    nameEn: "Qiao Lin Hotpot",
    lat: 47.61202,
    lng: -122.33347,
    address: "1510 7th Ave, Seattle, WA 98101（Downtown）",
    dataAddr: "Qiao Lin Hotpot, 1510 7th Ave, Seattle, WA 98101",
    tags: ["重庆火锅"],
    price: "$$$ · $30-60",
    visited: true,
    badges: ["🔥 Happy Hour 69折"],
    dishes: [
      { name: "一米肥牛", note: "必点" },
      { name: "现切牛仔肉", note: "招牌" },
      { name: "爽脆黑毛肚" },
      { name: "秘制牛舌 / 小郡肝" },
      { name: "鸳鸯锅（麻辣 + 番茄）", note: "推荐" },
    ],
    notes: [
      { type: "info", text: "🌶️ 辣锅不算很辣，不能吃辣也能接受。鸳鸯锅选麻辣+番茄最稳" },
      { type: "info", text: "🕐 Happy Hour 全场 69折：Sun-Thu 2-4PM & 8:30PM后，Fri-Sat 9:30PM后" },
      { type: "info", text: "🍦 小料台免费小菜（猪耳朵、凤爪、冰粉）+ 免费冰淇淋，适合朋友聚餐" },
      { type: "info", text: "🚗 不在 Ave 上，位于 Downtown。停车 $5/3hr。Yelp 可排队取号" },
    ],
  },
  {
    id: "Honeybee Fried Chicken",
    category: "chinese",
    name: "Honeybee Fried Chicken",
    nameEn: "Honeybee Fried Chicken",
    lat: 47.66441,
    lng: -122.31293,
    address: "4744 University Way NE 旁（岩茶隔壁）",
    tags: ["炸鸡 / 便当"],
    price: "$ · $8-15",
    visited: true,
    dishes: [
      { name: "炸鸡", note: "便宜划算" },
      { name: "便当" },
    ],
    notes: [
      { type: "info", text: "💡 岩茶旁边的炸鸡店，炸鸡很便宜很划算，便当也不错" },
    ],
  },
  {
    id: "rondo",
    category: "japanese",
    name: "Rondo",
    nameEn: "Japanese Kitchen",
    lat: 47.62074,
    lng: -122.32064,
    address: "224 Broadway E, Capitol Hill",
    dataAddr: "Rondo Japanese Kitchen, 224 Broadway E, Seattle, WA 98102",
    tags: ["日料 / 居酒屋风"],
    price: "$$ · $20-35",
    visited: true,
    dishes: [
      { name: "咖喱饭", note: "ZZ 亲自品尝" },
      { name: "奶油乌冬", note: "ZZ 亲自品尝" },
      { name: "日式定食 / 刺身 / 烤物" },
    ],
    notes: [
      { type: "info", text: "🚇 U District 站坐 Link 两站到 Capitol Hill，出站走一会儿就到。ZZ 亲自品尝过咖喱饭和奶油乌冬，值得专门跑一趟" },
    ],
  },
  {
    id: "天丼琥珀",
    category: "japanese",
    name: "天丼琥珀",
    nameEn: "Tendon Kohaku",
    lat: 47.597625, 
    lng: -122.327148,
    address: "504 5th Ave S, Suite 119, Chinatown-ID",
    dataAddr: "Tendon Kohaku, 504 5th Ave S, Suite 119, Seattle, WA 98104",
    tags: ["日式天妇罗丼"],
    price: "$$$ · $25-40",
    visited: false,
    badges: ["🔥 老吃家朋友认证：西雅图最好吃日料","🆕 2026.5 新开"],
    dishes: [
      { name: "天妇罗丼（招牌琥珀天丼）", note: "必点" },
      { name: "Kohaku Kabayaki Unagi Set", note: "Seattle 限定" },
    ],
    notes: [
      { type: "info", text: "🔥 老吃家朋友说是西雅图最好吃的日料！东京开过来的天妇罗专门店。Bellevue 老店常排 5 小时，2026 年 5 月新开了 Seattle CID 店。不在 Ave 上，还没去过，期待打卡" },
    ],
  },
  {
    id: "yu-sushi",
    category: "japanese",
    name: "Yu Sushi",
    nameEn: "Yu Sushi & Katsu",
    lat: 47.65771,
    lng: -122.31340,
    address: "4129 University Way NE",
    dataAddr: "Yu Sushi, 4129 University Way NE, Seattle, WA 98105",
    tags: ["日料 / 寿司"],
    price: "$$ · $20-35",
    visited: true,
    dishes: [
      { name: "寿喜锅", note: "ZZ 亲自品尝" },
      { name: "各类寿司卷 / 刺身" },
    ],
  },
  {
    id: "Sumo Sushi AYCE",
    category: "japanese",
    name: "Sumo Sushi AYCE",
    nameEn: "Sumo Sushi AYCE",
    lat: 47.66558,
    lng: -122.31285,
    address: "5000 University Way NE, Ste G",
    dataAddr: "Sumo Sushi, 5000 University Way NE, Ste G, Seattle, WA 98105",
    tags: ["日料自助"],
    price: "$$$ · $30-35/人",
    visited: true,
    dishes: [
      { name: "寿司卷 + 刺身 All You Can Eat" },
      { name: "Short Ribs / 三文鱼刺身", note: "推荐" },
    ],
    notes: [
      { type: "caution", text: "⚠️ \"和我们有 beef\"，品质不是很好 — 个人不推荐再去" },
    ],
  },
  {
    id: "u-don",
    category: "japanese",
    name: "U:Don",
    nameEn: "Japanese Noodle",
    lat: 47.66179,
    lng: -122.31330,
    address: "4515 University Way NE",
    dataAddr: "U:Don, 4515 University Way NE, Seattle, WA 98105",
    tags: ["日式乌冬"],
    price: "$ · ~$16",
    visited: true,
    badges: ["🔥 性价比高"],
    dishes: [
      { name: "乌冬面", note: "ZZ 亲自品尝" },
      { name: "Niku Dip Udon + 炸鸡", note: "必点" },
    ],
    notes: [
      { type: "info", text: "💡 乌冬面劲道，天妇罗现炸，份量充足，价格亲民" },
    ],
  },
  {
    id: "bob",
    category: "korean",
    name: "Bob",
    nameEn: "Korean",
    lat: 47.657890, 
    lng: -122.313559,
    address: "4732 University Way NE",
    tags: ["韩餐"],
    price: "$$ · $15-25",
    visited: true,
    dishes: [
      { name: "石锅拌饭（记得加个蛋）", note: "ZZ 每次必点" },
    ],
    notes: [
      { type: "info", text: "💡 ZZ 多次去吃，基本每次都是石锅拌饭加蛋" },
    ],
  },
  {
    id: "Korean Tofu House",
    category: "korean",
    name: "Korean Tofu House",
    nameEn: "Korean Tofu House",
    lat: 47.658280,
    lng: -122.314067,
    address: "4142 Brooklyn Ave NE",
    dataAddr: "Korean Tofu House, 4142 Brooklyn Ave NE, Seattle, WA 98105",
    tags: ["韩式豆腐汤"],
    price: "$$ · $18-30",
    visited: true,
    badges: ["🔥 雨天首选"],
    dishes: [
      { name: "豆腐汤 Combo（海鲜/牛肉）", note: "必点" },
      { name: "石锅拌饭" },
      { name: "海鲜煎饼（小菜可续）" },
    ],
    notes: [
      { type: "info", text: "💡 小菜很好吃（葱饼、鱼饼），还能续，西雅图雨天暖胃首选" },
    ],
  },
  {
    id: "egg-street",
    category: "korean",
    name: "Egg Street",
    nameEn: "2025 新开韩餐",
    lat: 47.66155,
    lng: -122.31330,
    address: "4507 University Way NE",
    tags: ["韩式简餐"],
    price: "$$ · $15-25",
    visited: false,
    badges: ["🆕 2025 新开"],
    dishes: [
      { name: "人参鸡腿汤", note: "推荐" },
      { name: "Mini V Kimbob" },
    ],
    notes: [
      { type: "info", text: "💡 韩国阿姨开的，超亲切，会免费送小菜和紫菜包饭，有 WiFi 适合学习" },
    ],
  },
  {
    id: "kong-tofu-house",
    category: "korean",
    name: "Kong Tofu House",
    nameEn: "豆腐汤",
    lat: 47.65860,
    lng: -122.31239,
    address: "1414 NE 42nd St, STE 103A（Ave 旁）",
    dataAddr: "Kong Tofu House, 1414 NE 42nd St, STE 103A, Seattle, WA 98105",
    tags: ["韩式豆腐汤"],
    price: "$$ · $18-28",
    visited: true,
    dishes: [
    ],
    notes: [
      { type: "info", text: "💡 ZZ 推荐 $25 左右套餐，有 Ribeye + 豆腐汤 + 饭，非常划算好吃" },
    ],
  },
  {
    id: "Sizzle & Crunch Vietnamese Grill",
    category: "southeast",
    name: "Sizzle & Crunch (苏州狂吃)",
    nameEn: "Sizzle & Crunch Vietnamese Grill",
    lat: 47.658316, 
    lng: -122.313678,
    address: "1313 NE 42nd St（Ave 拐角）",
    dataAddr: "Sizzle and Crunch, 1313 NE 42nd St, Seattle, WA 98105",
    tags: ["越南烤肉饭"],
    price: "$ · $10-13",
    visited: true,
    badges: ["🔥 午餐队伍通常很长"],
    dishes: [
      { name: "Pork Belly / 豆腐也不错" },
    ],
    notes: [
      { type: "info", text: "💡 ZZ 经常吃！便宜好吃，每次都点半牛半鸡，朋友推荐加 Pork Belly 和豆腐。担心味道淡可以要 extra soy sauce。期末图书馆赶 due 首选，自己买或让朋友带都在图书馆吃" },
    ],
  },
  {
    id: "thai-tom",
    category: "southeast",
    name: "Thai Tom",
    nameEn: "网红泰餐",
    lat: 47.66251,
    lng: -122.31329,
    address: "4543 University Way NE",
    dataAddr: "Thai Tom, 4543 University Way NE, Seattle, WA 98105",
    tags: ["泰餐"],
    price: "$$ · $20-30",
    visited: false,
    badges: ["🔥 不可错过"],
    dishes: [
      { name: "Pad Thai" },
      { name: "Panang Curry" },
      { name: "Yellow Curry" },
      { name: "芒果糯米饭", note: "🍬 甜口必试" },
    ],
    notes: [
      { type: "info", text: "🍬 芒果糯米饭!!! ⚠️ 记得带现金（Cash Only）" },
    ],
  },
  {
    id: "araya-s-place",
    category: "southeast",
    name: "Araya's Place",
    nameEn: "全素泰餐",
    lat: 47.66777,
    lng: -122.31269,
    address: "5240 University Way NE",
    dataAddr: "Araya's Place, 5240 University Way NE, Seattle, WA 98105",
    tags: ["泰式素食"],
    price: "$$ · $15-25",
    visited: false,
    dishes: [
      { name: "Tom Kha 汤", note: "必点" },
      { name: "Lunch Set" },
      { name: "drunken mushroom" },
    ],
  },
  {
    id: "pho-shizzle",
    category: "southeast",
    name: "Pho Shizzle",
    nameEn: "越南粉",
    lat: 47.65934,
    lng: -122.31334,
    address: "4235 University Way NE",
    dataAddr: "Pho Shizzle, 4235 University Way NE, Seattle, WA 98105",
    tags: ["越南 Pho"],
    price: "$$ · $15-20",
    visited: true,
    dishes: [
      { name: "Pho（越南牛肉粉）" },
      { name: "海南鸡饭（隐藏菜单！含糯米）", note: "🥇 必试" },
    ],
    notes: [
      { type: "info", text: "💡 隐藏菜单海南鸡饭可以试一下 听说味道不错！粉的分量还可以" },
    ],
  },
  {
    id: "Little Thai Restaurant",
    category: "southeast",
    name: "Little Thai Restaurant",
    nameEn: "Little Thai Restaurant",
    lat: 47.65812,
    lng: -122.31402,
    address: "4142 Brooklyn Ave NE #105（Ave 旁边）",
    dataAddr: "Little Thai Restaurant, 4142 Brooklyn Ave NE #105, Seattle, WA 98105",
    tags: ["泰餐"],
    price: "$ · $12-18",
    visited: true,
    dishes: [
      { name: "Pad Thai" },
      { name: "Pad See Ew / Drunken Noodle" },
      { name: "Green Curry / Panang Curry" },
    ],
    notes: [
      { type: "caution", text: "⚠️ 小红书对其评价不是很好 自己尝过他们家的curry 感觉还行" },
    ],
  },
  {
    id: "chipotle",
    category: "fastfood",
    name: "Chipotle",
    nameEn: "Mexican Grill",
    lat: 47.65879,
    lng: -122.31332,
    address: "4229 University Way NE",
    dataAddr: "Chipotle, 4229 University Way NE, Seattle, WA 98105",
    tags: ["墨西哥快餐"],
    price: "$ · $10-15",
    visited: true,
    dishes: [
      { name: "Burrito / Burrito Bowl" },
    ],
    notes: [
      { type: "info", text: "💡 经典连锁，稳定出品" },
    ],
  },
  {
    id: "raising-cane-s",
    category: "fastfood",
    name: "Raising Cane's",
    nameEn: "",
    lat: 47.66114,
    lng: -122.31346,
    address: "4345 University Way NE",
    dataAddr: "Raising Cane's, 4345 University Way NE, Seattle, WA 98105",
    tags: ["炸鸡"],
    price: "$ · $10-15",
    visited: false,
    badges: ["🆕 西雅图首店"],
    dishes: [
      { name: "Chicken Fingers Combo", note: "必点" },
      { name: "Cane's Sauce（甜口酱）", note: "🍬 灵魂蘸酱" },
      { name: "Texas Toast" },
    ],
    notes: [
      { type: "info", text: "西雅图第一家 Raising Cane's！开到凌晨2, 3点 适合作为夜宵" },
    ],
  },
  {
    id: "Cafe on the Ave",
    category: "fastfood",
    name: "Cafe on the Ave",
    nameEn: "Cafe on the Ave",
    lat: 47.65844,
    lng: -122.31339,
    address: "4201 University Way NE",
    tags: ["咖啡 / 餐厅"],
    price: "$$ · $15-25",
    visited: true,
    badges: ["🔥 转角地标"],
    dishes: [
      { name: "Kimchi Fried Rice", note: "ZZ 推荐" },
      { name: "Curry Rice", note: "ZZ 推荐" },
      { name: "奶油海鲜乌冬" },
      { name: "Japanese Short Cake（伯爵茶/草莓）", note: "隐藏菜单" },
    ],
    notes: [
      { type: "info", text: "💡 ZZ 在 Ave 上去的第一家餐厅！基本每次都吃 Kimchi Fried Rice 和 Curry Rice，分量很充足" },
    ],
  },
  {
    id: "Cultivate",
    category: "fastfood",
    name: "Cultivate UW",
    nameEn: "Cultivate",
    lat: 47.656819, 
    lng: -122.314778,
    address: "1218 NE Campus Pkwy, Elm Hall",
    dataAddr: "Cultivate UW, 1218 NE Campus Pkwy, Seattle, WA 98105",
    tags: ["新美式 Gastropub"],
    price: "$ · $8-15",
    visited: true,
    dishes: [
      { name: "NY Strip Steak Frites", note: "ZZ 亲自品尝推荐" },
      { name: "Pork Katsu Sandwich" },
      { name: "Chorizo Quesadilla" },
      { name: "Poutine / Fish & Chips" },
    ],
    notes: [
      { type: "info", text: "💡 UW 校内 Gastropub，食材来自 UW Farm 本地可持续种植。可用 Husky Card / Dining Plan。无小费。⚠️ 周末不营业。😉 如果学期末 Dining Plan 钱花不完，来 Cultivate 或者帮别人刷让他们转账，吃几次就花完了" },
    ],
  },
  {
    id: "don-t-yell-at-me",
    category: "dessert",
    name: "Don't Yell at Me",
    nameEn: "台湾奶茶",
    lat: 47.66169,
    lng: -122.31330,
    address: "4511 University Way NE",
    dataAddr: "Don't Yell at Me, 4511 University Way NE, Seattle, WA 98105",
    tags: ["台式奶茶"],
    price: "$ · $5-8",
    visited: true,
    dishes: [
      { name: "古早鲜奶茶 / 桂花茉莉鲜奶茶" },
    ],
  },
  {
    id: "岩茶",
    category: "dessert",
    name: "岩茶",
    nameEn: "YAN Tea",
    lat: 47.66441,
    lng: -122.31293,
    address: "4744 University Way NE C",
    tags: ["奶茶"],
    price: "$ · $6-9",
    visited: true,
    badges: ["🔥 西雅图奶茶天花板"],
    dishes: [
      { name: "Something Blue", note: "必点" },
      { name: "酸酪牛油果脆波波" },
      { name: "芝士奶盖青葡冰沙 / 轻卡黑提奶冰", note: "🍬 个人最爱" },
    ],
    notes: [
      { type: "info", text: "💡 被很多 UW 学生评为西雅图最好喝的奶茶" },
    ],
  },
  {
    id: "茶宴",
    category: "dessert",
    name: "茶宴",
    nameEn: "Chayan",
    lat: 47.65812,
    lng: -122.31402,
    address: "4106 Brooklyn Ave NE #103A",
    dataAddr: "Chayan, 4106 Brooklyn Ave NE #103A, Seattle, WA 98105",
    tags: ["奶茶"],
    price: "$ · $5-8",
    visited: true,
    dishes: [
    ],
    notes: [
      { type: "info", text: "其实个人觉得都还可以😅" },
    ],
  },
  {
    id: "grean-matcha",
    category: "dessert",
    name: "Grean Matcha",
    nameEn: "抹茶店",
    lat: 47.66201,
    lng: -122.31277,
    address: "4524 University Way NE",
    dataAddr: "Grean Matcha, 4524 University Way NE, Seattle, WA 98105",
    tags: ["抹茶 / 饮品"],
    price: "$ · $5-8",
    visited: true,
    dishes: [
      { name: "抹茶饮品 / 抹茶拿铁" },
    ],
    notes: [
      { type: "info", text: "💡 白天抹茶店，晚上变成 Elixir 甜品鸡尾酒吧" },
    ],
  },
  {
    id: "snooze",
    category: "dessert",
    name: "Snooze",
    nameEn: "雪花冰",
    lat: 47.65878,
    lng: -122.31336,
    address: "4213 University Way NE",
    dataAddr: "Snooze, 4213 University Way NE, Seattle, WA 98105",
    tags: ["雪花冰 / 甜品"],
    price: "$ · $8-12",
    visited: true,
    dishes: [
    ],
    notes: [
      { type: "caution", text: "⚠️ 要关门了，趁还在还可以再去一次！" },
    ],
  },
  {
    id: "snowy-village",
    category: "dessert",
    name: "Snowy Village",
    nameEn: "韩式雪花冰",
    lat: 47.66832,
    lng: -122.31283,
    address: "5264 University Way NE",
    dataAddr: "Snowy Village, 5264 University Way NE, Seattle, WA 98105",
    tags: ["韩式刨冰"],
    price: "$ · $10-15",
    visited: false,
    dishes: [
      { name: "芒果雪花冰", note: "🍬 必点" },
      { name: "紫薯 / 草莓 / 奥利奥雪花冰" },
    ],
    notes: [
      { type: "info", text: "🍬 韩式雪花冰专门店，比绵绵冰更细更绵，甜口不能错过" },
    ],
  },
  {
    id: "oh-bear",
    category: "dessert",
    name: "Oh Bear",
    nameEn: "鲷鱼烧 & 下午茶",
    lat: 47.66349,
    lng: -122.31617,
    address: "4708 11th Ave NE（Ave 旁边）",
    dataAddr: "Oh Bear Cafe & Teahouse, 4708 11th Ave NE, Seattle, WA 98105",
    tags: ["鲷鱼烧 / 甜品"],
    price: "$ · $5-10",
    visited: false,
    dishes: [
      { name: "提拉米苏鲷鱼烧", note: "🍬 必点" },
      { name: "甜品三明治" },
    ],
    notes: [
      { type: "info", text: "🍬 鲷鱼烧专门店！提拉米苏口味是甜口爱好者的隐藏宝藏" },
    ],
  },
  {
    id: "elixir",
    category: "dessert",
    name: "Elixir",
    nameEn: "甜品鸡尾酒吧",
    lat: 47.66201,
    lng: -122.31277,
    address: "4524 University Way NE（与 Grean Matcha 同址）",
    dataAddr: "Elixir, 4524 University Way NE, Seattle, WA 98105",
    tags: ["酒吧 / 甜品"],
    price: "$$ · $10-20",
    visited: false,
    badges: ["🆕 新开"],
    dishes: [
      { name: "甜品鸡尾酒" },
      { name: "Sweet Alchemy 冰淇淋" },
    ],
    notes: [
      { type: "info", text: "💡 白天 Grean Matcha，晚上变身甜品鸡尾酒吧。和 Sweet Alchemy 同老板" },
    ],
  }
];
